version: 2
updates:
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
    schedule:
      interval: "weekly"
    groups:
      julia-packages:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
