name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia 1.10 - ubuntu-latest - x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.10'
          arch: x64
      - uses: julia-actions/cache@v3
      - name: Install unregistered JuliQAOA dependency
        run: julia --project=. -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(url="https://github.com/lanl/JuliQAOA.jl")); Pkg.instantiate()'
      - name: Test
        run: julia --project=. -e 'import Pkg; Pkg.test(; coverage=false)'
